version: '2'

services:
    api:
        image: php:7.1-fpm
        restart: always
        ports:
          - "80:80"
        volumes:
            - ./:/var/www/html     
            - ./nginx:/etc/nginx/conf.d   
        env_file:
            - common.env
                
    postgres:
        image: postgres:11.5
        ports: 
           - "5432:5432"
        restart: always
        volumes:
           - $PWD/vendor/nasajon/bancosweb/dump:/docker-entrypoint-initdb.d/
        environment:
           - "POSTGRES_DB=desafio"
           - "POSTGRES_USER=postgres"
           - "POSTGRES_PASSWORD=postgres"
    
    tests:
        image: php:7.1-fpm
        # restart: always
        command: php vendor/bin/codecept run unit
        volumes:
            - ./:/var/www/html        
        env_file:
            - common.env
