imports:
    - { resource: services.yml }

framework:
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false